{% set name = "python-rapidjson" %}
{% set version = "0.9.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: ad80bd7e4bb15d9705227630037a433e2e2a7982b54b51de2ebabdd1611394a1

build:
  number: 1
  skip: True  # [py27]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - rapidjson
  requires:
    - pytest
    - pytz
  source_files:
    - tests
  commands:
    - pytest tests

about:
  home: https://github.com/python-rapidjson/python-rapidjson
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Python wrapper around rapidjson'
  description: |
    Python wrapper around RapidJSON. RapidJSON is an extremely fast C++ json serialization library.
    We do not support legacy python versions, you will need to upgrade to Python 3 to use this library.
  doc_url: https://python-rapidjson.readthedocs.io
  dev_url: https://github.com/python-rapidjson/python-rapidjson

extra:
  recipe-maintainers:
    - SylvainCorlay
    - hajapy
    - dbast
