{% set name = "python-rapidjson" %}
{% set version = "1.20" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 115f08c86d2df7543c02605e77c84727cdabc4b08310d2f097e953efeaaa73eb

build:
  number: 1
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - rapidjson
  requires:
    - pytest
    - pytz
  source_files:
    - tests
  commands:
    - pytest tests

about:
  home: https://github.com/python-rapidjson/python-rapidjson
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python wrapper around rapidjson
  description: |
    Python wrapper around RapidJSON. RapidJSON is an extremely fast C++ json serialization library.
    We do not support legacy python versions, you will need to upgrade to Python 3 to use this library.
  doc_url: https://python-rapidjson.readthedocs.io
  dev_url: https://github.com/python-rapidjson/python-rapidjson

extra:
  recipe-maintainers:
    - SylvainCorlay
    - hajapy
    - dbast
