appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: MdDqFwnLQ4RngvHkKdF+4knX41RloCFPHnCdzgtWrQIYNHBg4xVucDZE1RgM708kPNMtygAkLy1AvZObH/33pagrjaQotvEA+myWbwutSPjN9H0KNJ/JPFp9CFPYxqIdTtVgu0E/5PrRwM1FqcFVspqrYNDvpGMufKBfYm18ENrkkeu4/fvWwRdx2RtlCsZEO914HNU9ydlAs0k0IaYTErAz4CEqAzoqths4hQC4AiI5L5bsJkeHxTeYUeaWNdMYg2AV+NiPRUhvVba66u45KmFwD7o70EFWKp/4D5PgCDk3YPTXtWvjSpWPJyHfLEY1eOEpN8w6j/jDjDYdeDGk1CTej+TQnA4Cl3Er6XzU53VIpBy+nyMj/DTiNDs0NKWhsMc1Ix9JO2oN9Je/ItGlzDuyJ6r81slBz35NBUu8Wn3S8V8KZRcQuvk0CRb2nzigx1nEFAMIRAD68bbt56Mo1Ze21ZscmFO/PuNh5L9p4zNiamaTvaZkLPc2pbzH51zrYFLhlBesbU2UokQwDDn8NXnEJ+BSLQEDWQmhlGC4TaAf6wjL5Mss2hpxk9mcvF/xxkVxaDWwTedeYVqkAbvXBPK+xew4Fa4RTj0zZ0SatSf9qwj3VJEn5BtSlzIOewr77i3IDefNLk6PqkqdA6gdEZh31XWjmDIkh9CRj8VyffM=}
